NAV_ITEMS = (
    {
        "key": "datecalc",
        "href": "/tools/datecalc",
        "icon": "📆",
        "label": "日時計算",
        "description": "日時の加算・減算や差分を計算できます",
    },
    {
        "key": "calc",
        "href": "/tools/calc",
        "icon": "🧮",
        "label": "電卓",
        "description": "最もシンプルな電卓",
    },
    {
        "key": "rename",
        "href": "/tools/rename",
        "icon": "🔄",
        "label": "一括リネーム",
        "description": "アップロードしたファイル名を一括で変換",
    },
    {
        "key": "compress",
        "href": "/tools/compress",
        "icon": "📦",
        "label": "ファイル圧縮",
        "description": "アップロードしたファイルを圧縮",
    },
    {
        "key": "csvtool",
        "href": "/tools/csvtool",
        "icon": "📊",
        "label": "PowerCSV",
        "description": "CSV操作の専門ツール。編集・検証・変換をこれ一つで。",
    },
    {
        "key": "password_tool",
        "href": "/tools/password_tool",
        "icon": "🔐",
        "label": "Power IDeep",
        "description": "高レベルのIDパスワード管理ツール",
    },
    {
        "key": "workday",
        "href": "/tools/workday",
        "icon": "📅",
        "label": "営業日計算ツール",
        "description": "指定営業日を計算できます。",
    },
    {
        "key": "pdf_power",
        "href": "/tools/pdf_power",
        "icon": "📚",
        "label": "PowerPDF",
        "description": "PDFを操作する汎用ツール",
    },
    {
        "key": "color_extract",
        "href": "/tools/color_extract",
        "icon": "🎨",
        "label": "抜き出しツール",
        "description": "PDF/画像の指定色を抽出・除外・置換。スポイトとリアルタイムプレビュー対応",
    },
    {
        "key": "powerstamp",
        "href": "/tools/powerstamp",
        "icon": "🖋️",
        "label": "PowerSTAMP",
        "description": "スキャン背景に文字・図形・画像を重ね、背景抜きで印刷",
    },
    {
        "key": "share",
        "href": "/tools/share",
        "icon": "📪️",
        "label": "FILE POST",
        "description": "ファイル共有ツール",
    },
    {
        "key": "car_inspe",
        "href": "/tools/car_inspe",
        "icon": "📄",
        "label": "車検証ツール",
        "description": "車検証の読み取りツール",
    },
    {
        "key": "shiftersync",
        "href": "/tools/shiftersync",
        "icon": "👥",
        "label": "ShifterSync",
        "description": "シフト作成を更に効率化",
    },
    {
        "key": "leave_mgr",
        "href": "/tools/leave_mgr",
        "icon": "⛵",
        "label": "有休共有ツール",
        "description": "運転士の有休日を共有",
    },
    {
        "key": "monthly_generator",
        "href": "/tools/monthly_generator",
        "icon": "📝",
        "label": "月次ジェネレーター",
        "description": "面倒な月次報告書の数値入力を自動で",
    },
    {
        "key": "subject_analysis_tool",
        "href": "/tools/subject_analysis_tool",
        "icon": "⚖️",
        "label": "科目別分析ツール SAT",
        "description": "現場収支の分析をお手伝い",
    },
    {
        "key": "pluslist",
        "href": "/tools/pluslist",
        "icon": "📛",
        "label": "社員名簿PLUS",
        "description": "高速で多機能な名簿機能をあなたに",
    },
    {
        "key": "siteplus",
        "href": "/tools/siteplus",
        "icon": "🏗️",
        "label": "現場リストPLUS",
        "description": "契約番号と枝番号をAPI前提で管理する現場マスタ",
    },
    {
        "key": "powervote",
        "href": "/tools/powervote",
        "icon": "🖐",
        "label": "PowerVote",
        "description": "自由度の高い投票・アンケート収集ツール",
    },
    {
        "key": "power_flow",
        "href": "/tools/power_flow",
        "icon": "🧭",
        "label": "Power Flow",
        "description": "フローチャートを作成・整列・出力できる作図ツール",
    },
)
