NAV_ITEMS = (
    {
        "key": "datecalc",
        "href": "/tools/datecalc",
        "icon": "📆",
        "label": "日時計算",
        "description": "日時の加算・減算や差分を計算できます",
    },
    {
        "key": "calc",
        "href": "/tools/calc",
        "icon": "🧮",
        "label": "電卓",
        "description": "まぁまぁ便利な電卓",
    },
    {
        "key": "rename",
        "href": "/tools/rename",
        "icon": "🔄",
        "label": "一括リネーム",
        "description": "アップロードしたファイル名を一括で変換",
    },
    {
        "key": "compress",
        "href": "/tools/compress",
        "icon": "📦",
        "label": "ファイル圧縮",
        "description": "アップロードしたファイルを圧縮",
    },
    {
        "key": "csvtool",
        "href": "/tools/csvtool",
        "icon": "📊",
        "label": "PowerCSV",
        "description": "CSV操作の専門ツール。編集・検証・変換をこれ一つで。",
    },
    {
        "key": "password_tool",
        "href": "/tools/password_tool",
        "icon": "🔐",
        "label": "Power IDeep",
        "description": "高レベルのIDパスワード管理ツール",
    },
    {
        "key": "workday",
        "href": "/tools/workday",
        "icon": "📅",
        "label": "営業日計算ツール",
        "description": "指定営業日を計算できます。",
    },
    {
        "key": "pdf_power",
        "href": "/tools/pdf_power",
        "icon": "📚",
        "label": "PowerPDF",
        "description": "PDFを操作する汎用ツール",
    },
    {
        "key": "color_extract",
        "href": "/tools/color_extract",
        "icon": "🎨",
        "label": "抜き出しツール",
        "description": "PDF/画像の指定色を抽出・除外・置換。スポイトとリアルタイムプレビュー対応",
    },
    {
        "key": "powerstamp",
        "href": "/tools/powerstamp",
        "icon": "🖋️",
        "label": "PowerSTAMP",
        "description": "スキャン背景に文字・図形・画像を重ね、背景抜きで印刷",
    },
    {
        "key": "share",
        "href": "/tools/share",
        "icon": "📪️",
        "label": "FILE POST",
        "description": "ファイル共有ツール",
    },
    {
        "key": "car_inspe",
        "href": "/tools/car_inspe",
        "icon": "🚗",
        "label": "マイカー管理ツール",
        "description": "営業所ごとに運転士の車検証・自賠責・任意保険・免許証の期限を管理し、期限前にメール通知",
    },
    {
        "key": "shiftersync",
        "href": "/tools/shiftersync",
        "icon": "👥",
        "label": "ShifterSync",
        "description": "シフト作成を更に効率化",
    },
    {
        "key": "leave_mgr",
        "href": "/tools/leave_mgr",
        "icon": "⛵",
        "label": "有休共有ツール",
        "description": "運転士の有休日を共有",
    },
    {
        "key": "monthly_generator",
        "href": "/tools/monthly_generator",
        "icon": "📝",
        "label": "月次ジェネレーター",
        "description": "面倒な月次報告書の数値入力を自動で",
    },
    {
        "key": "subject_analysis_tool",
        "href": "/tools/subject_analysis_tool",
        "icon": "⚖️",
        "label": "科目別分析ツール SAT",
        "description": "現場収支の分析をお手伝い",
    },
    {
        "key": "pluslist",
        "href": "/tools/pluslist",
        "icon": "📛",
        "label": "社員名簿PLUS",
        "description": "高速で多機能な名簿機能をあなたに",
    },
    {
        "key": "siteplus",
        "href": "/tools/siteplus",
        "icon": "🏗️",
        "label": "現場リストPLUS",
        "description": "契約番号と枝番号をAPI前提で管理する現場マスタ",
    },
    {
        "key": "health_check",
        "href": "/tools/health_check",
        "icon": "🩺",
        "label": "健診PLUS",
        "description": "健康診断の予約・受診・再検査・二次検査を年度ごとに抜け漏れなく管理",
    },
    {
        "key": "to_bell",
        "href": "/tools/to_bell",
        "icon": "🔔",
        "label": "To Bell",
        "description": "タスク、確認依頼、期限、他ツール通知をまとめて操縦する仕事の司令塔",
    },
    {
        "key": "powervote",
        "href": "/tools/powervote",
        "icon": "🖐",
        "label": "PowerVote",
        "description": "自由度の高い投票・アンケート収集ツール",
    },
    {
        "key": "power_flow",
        "href": "/tools/power_flow",
        "icon": "🧭",
        "label": "Power Flow",
        "description": "フローチャートを作成・整列・出力できる作図ツール",
    },
    {
        "key": "power_imager",
        "href": "/tools/power_imager",
        "icon": "🖼️",
        "label": "PowerImager",
        "description": "プロレベルの画像編集をここに",
    },
    {
        "key": "bus_pricing",
        "href": "/tools/bus_pricing",
        "icon": "🚌",
        "label": "貸切料金計算ツール",
        "description": "貸切バスの公示下限額と改善基準告示の監査をまとめて確認",
    },
)
