NAV_ITEMS = (
    {
        "href": "/tools/datecalc",
        "icon": "📆",
        "label": "日時計算",
        "description": "日時の加算・減算や差分を計算できます",
    },
    {
        "href": "/tools/calc",
        "icon": "🧮",
        "label": "電卓",
        "description": "最もシンプルな電卓",
    },
    {
        "href": "/tools/rename",
        "icon": "🔄",
        "label": "一括リネーム",
        "description": "アップロードしたファイル名を一括で変換",
    },
    {
        "href": "/tools/compress",
        "icon": "📦",
        "label": "ファイル圧縮",
        "description": "アップロードしたファイルを圧縮",
    },
    {
        "href": "/tools/csvtool",
        "icon": "📊",
        "label": "PowerCSV",
        "description": "CSV操作の専門ツール。編集・検証・変換をこれ一つで。",
    },
    {
        "href": "/tools/password_tool",
        "icon": "🔐",
        "label": "パスワード生成・管理ツール",
        "description": "強固なパスワードを生成 管理することができます。",
    },
    {
        "href": "/tools/workday",
        "icon": "📅",
        "label": "営業日計算ツール",
        "description": "指定営業日を計算できます。",
    },
    {
        "href": "/tools/pdf_power",
        "icon": "📚",
        "label": "PowerPDF",
        "description": "PDFを操作する汎用ツール",
    },
    {
        "href": "/tools/color_extract",
        "icon": "🎨",
        "label": "抜き出しツール",
        "description": "PDF/画像の指定色を抽出・除外・置換。スポイトとリアルタイムプレビュー対応",
    },
    {
        "href": "/tools/powerstamp",
        "icon": "🖋️",
        "label": "PowerSTAMP",
        "description": "スキャン背景に文字・図形・画像を重ね、背景抜きで印刷",
    },
    {
        "href": "/tools/share",
        "icon": "📪️",
        "label": "FILE POST",
        "description": "ファイル共有ツール",
    },
    {
        "href": "/tools/car_inspe",
        "icon": "📄",
        "label": "車検証ツール",
        "description": "車検証の読み取りツール",
    },
    {
        "href": "/tools/shiftersync",
        "icon": "👥",
        "label": "ShifterSync",
        "description": "シフト作成を更に効率化",
    },
    {
        "href": "/tools/leave_mgr",
        "icon": "⛵",
        "label": "有休共有ツール",
        "description": "運転士の有休日を共有",
    },
    {
        "href": "/tools/monthly_generator",
        "icon": "📝",
        "label": "月次ジェネレーター",
        "description": "面倒な月次報告書の数値入力を自動で",
    },
    {
        "href": "/tools/subject_analysis_tool",
        "icon": "⚖️",
        "label": "科目別分析ツール SAT",
        "description": "現場収支の分析をお手伝い",
    },
    {
        "href": "/tools/pluslist",
        "icon": "📛",
        "label": "社員名簿PLUS",
        "description": "高速で多機能な名簿機能をあなたに",
    },
)
